In [2]:
import numpy as np
from scipy.sparse.linalg import svds
U=np.random.randn(10,5)
V=np.random.randn(7,5)
X=U.dot(V.T)
(u,s,v)=svds(X, k=5)

In [9]:
def svdsUV(U,V):
    (qu,ru)=np.linalg.qr(U)
    (qv,rv)=np.linalg.qr(V)
    [ur,sr,vr]=np.linalg.svd(ru.dot(rv.T))
    return (qu.dot(ur), sr, qv.dot(vr.T).T)

array([[-0.23868799, -0.82753961, -2.62567856,  1.74765073,  3.37407628,
        -0.48732915, -1.59696878],
       [ 0.7631659 ,  0.42654975, -1.33840424,  2.44279001,  2.75913014,
         0.57099711, -0.76620679],
       [ 0.62688355,  3.07089545,  1.04605404,  0.26727578,  4.28092262,
        -2.83157715,  2.81104266],
       [ 0.17622747,  1.03292087, -0.14826616,  2.19460708,  1.84927247,
         0.44627936, -0.89951697],
       [ 0.16860622, -0.27396657,  0.60812835,  1.91431545, -0.88315135,
         1.75412725, -1.3121396 ],
       [-0.96115466, -0.42231978, -1.01648389, -2.48106451, -2.18367128,
         0.0975694 , -0.79599966],
       [-0.60288369, -3.55711375, -1.18145318, -0.35627662, -0.82511391,
        -0.14528863, -0.92579044],
       [-0.73873766, -5.78110229,  1.27624081,  0.30643224, -5.9846945 ,
         2.6364832 , -2.07820139],
       [ 0.43747563,  2.00567263, -0.57631576,  1.33374208,  3.67191722,
        -1.07651122,  0.49925046],
       [-1.93358173,  3.4838

In [30]:
sr

array([13.25978989,  7.66626069,  5.82830578,  3.580559  ,  1.20648754])

In [29]:
sr

array([13.25978989,  7.66626069,  5.82830578,  3.580559  ,  1.20648754])

In [31]:
s

array([ 1.20648754,  3.580559  ,  5.82830578,  7.66626069, 13.25978989])